# Generated by Django 4.2.30 on 2026-07-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="long_description_html",
            field=models.TextField(
                blank=True,
                help_text="Rich HTML shown in the product page Description tab",
            ),
        ),
    ]
