# Generated by Django 4.2.30 on 2026-07-08 12:55
#
# Some deployed databases had `users_user` created by an earlier version of
# 0001_initial (before phone/sms_opt_in/created_at existed) but were already
# recorded as migrated, so Django won't reapply 0001_initial to add them.
# Uses IF NOT EXISTS so it's a no-op on databases that already have the
# columns (e.g. freshly migrated ones).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE users_user ADD COLUMN IF NOT EXISTS phone varchar(30) NOT NULL DEFAULT '';
                ALTER TABLE users_user ADD COLUMN IF NOT EXISTS sms_opt_in boolean NOT NULL DEFAULT false;
                ALTER TABLE users_user ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[],
        ),
    ]
